#!/usr/bin/env bash
# Script that displays username, UID, and home directory from /etc/passwd

while IFS=: read -r username _ uid _ _ home _; do
    printf "%s:%s:%s\n" "$username" "$uid" "$home"
done < /etc/passwd