#!/usr/bin/env bash
#This script prints "To infinity and beyond" indefinitely with a 2-second pause
# shellcheck disable=SC2009

PID_FILE="/var/run/my_process.pid"
DAEMON="./manage_my_process"

case "$1" in
    start)
        $DAEMON &
        echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat $PID_FILE)"
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat $PID_FILE)"
            rm -f "$PID_FILE"
        fi
        $DAEMON &
        echo $! > $PID_FILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
