#!/usr/bin/env bash
#This script prints "To infinity and beyond" indefinitely with a 2-second pause
# shellcheck disable=SC2009

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
    # Fon rejimində proses başlat və PID faylına yaz
    ./$PROCESS_NAME &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if kill "$PID" 2>/dev/null; then
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "Process not running, removing PID file"
            rm -f "$PID_FILE"
        fi
    else
        echo "Process not running"
    fi
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        stop_process
        start_process
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
