#!/usr/bin/env bash
#Script that displays its own PID.
# shellcheck disable=SC2009
for pid in /proc/[0-9]*; do
    if [ -f "$pid/comm" ]; then
        name=$(cat "$pid/comm")
        if [[ $name == *bash* ]]; then
            echo "$(basename $pid) $name"
        fi
    fi
done

