#!/usr/bin/env bash
#This script prints "To infinity and beyond" indefinitely with a 2-second pause
# shellcheck disable=SC2009
pid=$(ps aux | grep 4-to_infinity_and_beyond | grep -v grep | awk '{print $2}')

echo 9 > "/proc/$pid/kill"
