#!/usr/bin/env bash
#This script prints "To infinity and beyond" indefinitely with a 2-second pause
# shellcheck disable=SC2009

PID=$(pgrep -f 7-highlander)

if [ -n "$PID" ]
then
    kill -s SIGTERM "$PID"
fi
