#!/usr/bin/env bash
#This script prints "To infinity and beyond" indefinitely with a 2-second pause
# shellcheck disable=SC2009

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
